---

# Dump do banco de dados MySQL
- hosts: 192.168.1.27
  user: root

  tasks:

    - name: Dump do banco de dados MySQL 
      mysql_db:
          login_user: root
          login_password: boreal1408psql
          state: dump
          name: all
          target: /root/mariadb.sql

# Dump do banco de dados PostgreSQL 
#- hosts: 192.168.1.27
#  user: root

#  tasks:

#    - name: Dump do banco de dados PostgreSQL  
#      postgresql_db:
#          login_user: postgres 
#          #login_password: boreal1408psql 
#          state: dump
#          name: bacula 
#          target: /root/postgresql.sql


# Sincronização dos arquivos de paginas web. 
- hosts: 192.168.1.4
  user: root

  tasks:

     - name: RSYNC paginas web
       synchronize:
           mode: pull
           src: /var/www
           dest: /home/eduardo/bkp_servidores/{{ansible_nodename}}
           recursive: yes
           delete: yes
           group: yes
           links: yes
           owner: yes
           perms: yes
           times: yes
           compress: yes

# Sincronização de todos os arquivos importantes dos servidores
- hosts: slackware debian centos vms 
  user: root
  
  tasks:

     - name: RSYNC Slacks, VMs e NFS
       synchronize:
           mode: pull
           src: /etc /home/eduardo /usr/local /opt /root
           dest: /home/eduardo/bkp_servidores/{{ansible_nodename}}
           recursive: yes
           delete: yes
           group: yes
           links: yes
           owner: yes
           perms: yes
           times: yes
           compress: yes




...
