---

- hosts: vms

  tasks:

    - name: Atualizacao repositorio Debian.
      apt: update_cache=yes
      when: ansible_os_family == 'Debian'

    - name: Atualizacao sistema Debian.
      apt: upgrade=dist
      when: ansible_os_family == 'Debian'

    - name: Instalação de pacotes.
      apt:
        pkg:
        - vim                  # Editor de texto completo, melhor que o padrao vim-tiny.
        - inxi                 # Informacoes do sistema.
        - htop                 # Exibicao de processos.
        - iptables             # Firewall para ser usado em conjunto com fail2ban.
        - fail2ban             # Protecao contra ataques de forcao bruta.
        - git                  # Controle de versao de arquivos, util para baixar pacotes do repo github.
        - curl                 # Transferencia de dados usando URLs.
        - iwatch               # Monitoramento arquivos e diretorios.
        - msmtp                # Programa simples para envio de emails.
        - msmtp-mta            # Servidor simples MTA para envio de e-mails.
        #- bsd-mailx            # Cliente de linha de comando para envio de emails manual.
        - apticron             # Checagem em tempos por atualizacoes no Debian e notifica por email.
        - logwatch             # Inforcoes do estado do sistema, envio diario por e-mail.
        - bash-completion      # Opcao mais completa para completar comandos do bash.
        #- fdupes               # identificar arquivos duplicados.
        - rsync                # Sincronizacao de arquivos.
        - zstd                 # Compactador zst.


    - name: Copia local do arquivo de configuracao fail2ban para srv remoto.
      copy:
        src: /etc/ansible/arquivos/etc/fail2ban/jail.local
        dest: /etc/fail2ban/jail.local

    - name: Copia local do arquivo de configuracao iwatch.xml p/ iwatch.xml.ori.
      shell: cp /etc/iwatch/iwatch.xml /etc/iwatch/iwatch.xml.ori

    - name: Copia local do arquivo de configuracao iwatch para srv remoto.
      copy:
        src: /etc/ansible/arquivos/etc/iwatch/iwatch.xml
        dest: /etc/iwatch/iwatch.xml

    - name: Copia local do arquivo de configuracao msmtp para srv remoto.
      copy:
        src: /etc/ansible/arquivos/root/.msmtprc
        dest: /root/.msmtprc

    - name: Copia local do arquivo de configuracao apticron para srv remoto.
      copy:
        src: /etc/ansible/arquivos/etc/apticron/apticron.conf
        dest: /etc/apticron/apticron.conf

    - name: Copia local do arquivo de configuracao logwatch para srv remoto .
      copy:
        src: /etc/ansible/arquivos/etc/logwatch/conf/logwatch.conf
        dest: /etc/logwatch/conf/logwatch.conf

    - name: Copia local do arquivo .bashrc para Eduardo remoto.
      copy:
        src: /etc/ansible/arquivos/home/eduardo/.bashrc
        dest: /home/eduardo/.bashrc

    - name: Copia local do arquivo .bashrc para Root remoto.
      copy:
        src: /etc/ansible/arquivos/root/.bashrc
        dest: /root/.bashrc

#    - name: Copia local do arquivo de configuracao /etc/pam.d/su para srv remoto.
#      copy:
#        src: /etc/ansible/arquivos/etc/pam.d/su
#        dest: /etc/pam.d/su

    - name: Copia local do arquivo de configuracao /etc/pam.d/su para srv remoto.
      shell: echo "auth       required   pam_wheel.so" >> /etc/pam.d/su

#    - name: Criar grupo de suporte no srv Linux.
#      shell: groupadd suporte

#    - name: Copia local do arquivo de configuracao /etc/sudoers para srv remoto.
#      copy:
#        src: /etc/ansible/arquivos/etc/sudoers
#        dest: /etc/sudoers

    - name: Iniciar servicos e configurar para iniciarem junto com sistema.
      shell: systemctl restart fail2ban && systemctl enable fail2ban && systemctl restart iwatch && systemctl enable iwatch

...
