---

- hosts: vms

  tasks:

    - name: Atualizacao repositorio Debian.
      apt: update_cache=yes
      when: ansible_os_family == 'Debian'

    - name: Atualizacao sistema Debian.
      apt: upgrade=dist
      when: ansible_os_family == 'Debian'

    - name: Instalação de pacotes pré compilados.
      apt:
        pkg:
        - vim                  # Editor de texto completo, melhor que o padrao vim-tiny.
        - inxi                 # Informacoes do sistema.
        - htop                 # Exibicao de processos.
        - iptables             # Firewall para ser usado em conjunto com fail2ban.
        - fail2ban             # Protecao contra ataques de forcao bruta.
        - git                  # Controle de versao de arquivos, util para baixar pacotes do repo github.
        - curl                 # Transferencia de dados usando URLs.
        - iwatch               # Monitoramento arquivos e diretorios.
        - msmtp                # Programa simples para envio de emails.
        - msmtp-mta            # Servidor simples MTA para envio de e-mails.
        #- bsd-mailx            # Cliente de linha de comando para envio de emails manual.
        - apticron             # Checagem em tempos por atualizacoes no Debian e notifica por email.
        - logwatch             # Inforcoes do estado do sistema, envio diario por e-mail.
        - bash-completion      # Opcao mais completa para completar comandos do bash.
        #- fdupes               # identificar arquivos duplicados.
        - rsync                # Sincronizacao de arquivos.
        - zstd                 # Compactador zst.
        #- openssh-server       # Servidor SSH.


    - name: Garantir existencia do grupo "wheel".
      ansible.builtin.group:
        name: wheel
        state: present

    - name: Incluir user eduardo no grupo wheel.
      shell: usermod -aG wheel eduardo

    - name: SSH - Copia de arquivo e backup.
      ansible.builtin.copy:
        src: /etc/ansible/arquivos/srv/etc/ssh/sshd_config
        dest: /etc/ssh/sshd_config
        backup: yes

    - name: SU - Copia de arquivo e backup.
      ansible.builtin.copy:
        src: /etc/ansible/arquivos/srv/etc/pam.d/su
        dest: /etc/pam.d/su
        backup: yes

    - name: Fail2ban - Copia de arquivo e backup.
      ansible.builtin.copy:
        src: /etc/ansible/arquivos/srv/etc/fail2ban/jail.local
        dest: /etc/fail2ban/jail.local
        backup: yes

    - name: Iwatch - Copia de arquivo e backup.
      ansible.builtin.copy:
        src: /etc/ansible/arquivos/srv/etc/iwatch/iwatch.xml
        dest: /etc/iwatch/iwatch.xml
        backup: yes

    - name: Msmtp - Copia de arquivo e backup.
      ansible.builtin.copy:
        src: /etc/ansible/arquivos/srv/root/.msmtprc
        dest: /root/.msmtprc
        backup: yes

    - name: Apticron - Copia de arquivo e backup.
      ansible.builtin.copy:
        src: /etc/ansible/arquivos/srv/etc/apticron/apticron.conf
        dest: /etc/apticron/apticron.conf
        backup: yes

    - name: Logwatch - Copia de arquivo e backup.
      ansible.builtin.copy:
        src: /etc/ansible/arquivos/srv/etc/logwatch/conf/logwatch.conf
        dest: /etc/logwatch/conf/logwatch.conf
        backup: yes

    - name: Bash Usuario Eduardo - Ajuste do shell de usuario.
      ansible.builtin.copy:
        src: /etc/ansible/arquivos/srv/home/eduardo/.bashrc
        dest: /home/eduardo/.bashrc
        backup: yes

    - name: Bash Usuario Root - Ajuste do shell de usuario Root.
      ansible.builtin.copy:
        src: /etc/ansible/arquivos/srv/root/.bashrc
        dest: /root/.bashrc
        backup: yes

    - name: Iniciar servicos e habilitar iniciarem junto com sistema.
      shell: systemctl restart fail2ban && systemctl enable fail2ban && systemctl restart iwatch && systemctl enable iwatch

    - name: Zabbix - Download de pacote.
      ansible.builtin.get_url:
        url: https://repo.zabbix.com/zabbix/7.0/debian/pool/main/z/zabbix-release/zabbix-release_7.0-2+debian12_all.deb
        dest: /root/install/
      ansible.builtin.get_url:
        url: https://sourceforge.net/projects/bacula/files/bacula/15.0.2/bacula-15.0.2.tar.gz
        dest: /root/install/


    - name: Instalacao zabbix-agent.
      shell: mkdir /root/install && cd /root/install && wget https://repo.zabbix.com/zabbix/7.0/debian/pool/main/z/zabbix-release/zabbix-release_7.0-2+debian12_all.deb && dpkg -i zabbix-release_7.0-2+debian12_all.deb && apt update && apt install zabbix-agent2 zabbix-agent2-plugin-* && systemctl restart zabbix-agent2 && systemctl enable zabbix-agent2

    - name: Instalacao glpi-agent.
      shell: rsync -e "ssh -p 839" -ru /etc/ansible/arquivos/srv/root/install/glpi-agent* root@192.168.1.163:/root/install/ && apt install -y /root/install/glpi-agent* && rsync -e "ssh -p 839" -ru /etc/ansible/arquivos/srv/etc/glpi-agent/agent.cfg root@192.168.1.163:/etc/glpi-agent/agent.cfg && systemctl start glpi-agent && systemctl enable glpi-agent

    - name: Download pacote bacula - FD.
      get_url:
              url: https://sourceforge.net/projects/bacula/files/bacula/15.0.2/bacula-15.0.2.tar.gz
              dest: /root/install/bacula/

    - name: Descompactacao pacote bacula.
      shell: cd /root/install/bacula/ && tar -xvzf bacula-15.0.2.tar.gz

    - name: Configuracao instalacao bacula.
      shell: cd /root/install/bacula/bacula-15.0.2/ && ./configure --enable-client-only --enable-build-dird=no --enable-build-stored=no --bindir=/usr/bin --sbindir=/usr/sbin --with-scriptdir=/etc/bacula/scripts --with-working-dir=/var/lib/bacula --with-logdir=/var/log --enable-smartalloc

    - name: Instalacao bacula - FD.
      shell: cd /root/install/bacula/bacula-15.0.2 && make -j8 && make install && make install-autostart-fd

    - name: Reiniciando servicos - FD.
      shell: systemctl restart bacula-fd

...
