---

- hosts: 192.168.1.3

  tasks:

    - name: Atualizacao repositorio Debian.
      apt: update_cache=yes
      when: ansible_os_family == 'Debian'

    - name: Atualizacao sistema Debian.
      apt: upgrade=dist
      when: ansible_os_family == 'Debian'

    - name: Instalação de pacotes.
      apt:
        pkg:
        - vim
        - inxi
        - htop
        - fail2ban
        - git
        - iwatch
        - curl
        - mailutils
        - libsasl2-modules
        - postfix
        - bash-completion
#        - rclone
#        - fdupes
        - rsync
        - zstd

    - name: Copia arquivos de configuracao fail2ban, iwatch e postfix.
      shell: cp -p /etc/fail2ban/jail.conf /etc/fail2ban/jail.local && cp -p /etc/iwatch/iwatch.xml /etc/iwatch/iwatch.xml.ori && cp /etc/postfix/main.cf /etc/postfix/main.cf.ori

    - name: Fail2ban - Sincronizacao de arquivos de configuracao modelo 192.168.1.5.
      shell: rsync -e "ssh -p 839" -ru root@192.168.1.5:/etc/fail2ban/jail.local /etc/fail2ban/jail.local

    - name: Iwatch - Sincronizacao de arquivos de configuracao modelo 192.168.1.5.
      shell: rsync -e "ssh -p 839" -ru root@192.168.1.5:/etc/iwatch/iwatch.xml /etc/iwatch/iwatch.xml

    - name: Postfix - Sincronizacao de arquivos de configuracao modelo 192.168.1.5.
      shell: rsync -e "ssh -p 839" -ru root@192.168.1.5:/etc/postfix/sasl/sasl_passwd /etc/postfix/sasl/sasl_passwd

    - name: Postfix - Criacao e protecao do db de hash.
      shell: postmap /etc/postfix/sasl/sasl_passwd && chown root:root /etc/postfix/sasl/sasl_passwd /etc/postfix/sasl/sasl_passwd.db && chmod 0600 /etc/postfix/sasl/sasl_passwd /etc/postfix/sasl/sasl_passwd.db

    - name: Fail2ban - Iniciar junto com sistema.
      shell: systemctl start fail2ban && systemctl enable fail2ban

    - name: Instalacao zabbix-agent.
      shell: mkdir /root/install && cd /root/install && wget https://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix-release/zabbix-release_6.0-5+debian12_all.deb && dpkg -i zabbix-release_6.0-5+debian12_all.deb && apt update && apt install zabbix-agent && systemctl restart zabbix-agent && systemctl enable zabbix-agent

    - name: Instalacao glpi-agent.
      shell: rsync -e "ssh -p 839" -ru root@192.168.1.5:/install/glpi-agent* /root/install/ && apt install -y /root/install/glpi-agent* && rsync -e "ssh -p 839" -ruv root@192.168.1.5:/etc/glpi-agent/agent.cfg /etc/glpi-agent/agent.cfg && systemctl start glpi-agent && systemctl enable glpi-agent

    - name: Instalacao bacula-fd.
      shell:
...
