---

- hosts: debian

  tasks:

    - name: Atualizacao repositorio Debian
      apt: update_cache=yes
      when: ansible_os_family == 'Debian'

    - name: Atualizacao sistema Debian
      apt: upgrade=dist
      when: ansible_os_family == 'Debian'

    - name: Atualizacao sistema RedHat
      yum: name=* state=latest
      when: ansible_os_family == 'RedHat'

    #- name: Reiniciando os servidores
    #  shell: sleep 2 && reboot -n
    #  async: 1
    #  poll: 0
    #  ignore_errors: true

#    - name: Esperando os servidores voltarem
#      local_action: wait_for host={{ ansible_ssh_host }} state=started delay=30

...
