---

### CONTROLADOR DE DOMINIO DC2
- hosts: 192.168.1.41
  user: root

  tasks:
     - name: Checando os databases.
       shell: /usr/local/samba/bin/samba-tool dbcheck --cross-ncs && /usr/local/samba/bin/samba-tool dbcheck --cross-ncs --fix

     - name: Download pacote recente do samba-4
       shell: cd /root/samba && wget https://download.samba.org/pub/samba/samba-latest.tar.gz

     - name: Descompactacao pacote samba-4.
       shell: cd /root/samba/ && tar -xvzf samba-latest.tar.gz

#     - name: Instalacao de dependencias
#       shell: cd /root/samba/samba-4* && bootstrap/generated-dists/debian12/bootstrap.sh

     - name: Parando servicos do samba-4.
       shell: systemctl stop samba-ad-dc

     - name: Update do samba-4.
       shell: cd /root/samba/samba-4* && ./configure && make && make install

     - name: Organizacao de pacotes e pastas.
       shell: rm -rf /root/samba/samba-latest.tar.gz && mv /root/samba/samba-4* /root/samba/tar_old/

     - name: Iniciando o servico do samba4
       shell: systemctl start samba-ad-dc && systemctl restart samba-ad-dc

     - name: Checando os databases
       shell: /usr/local/samba/bin/samba-tool dbcheck --cross-ncs && /usr/local/samba/bin/samba-tool dbcheck --cross-ncs --fix

     - name: Reiniciando o servidor
       shell: sleep 2 && reboot -n
       async: 1
       poll: 0
       ignore_errors: true

     - name: Esperando o servidor voltar
       local_action: wait_for host={{ ansible_ssh_host }} state=started delay=30

### CONTROLADOR DE DOMINIO DC1
- hosts: 192.168.1.40
  user: root

  tasks:
     - name: Checando os databases.
       shell: /usr/local/samba/bin/samba-tool dbcheck --cross-ncs && /usr/local/samba/bin/samba-tool dbcheck --cross-ncs --fix

     - name: Download pacote recente do samba-4
       shell: cd /root/samba && wget https://download.samba.org/pub/samba/samba-latest.tar.gz

     - name: Descompactacao pacote samba-4.
       shell: cd /root/samba/ && tar -xvzf samba-latest.tar.gz

#     - name: Instalacao de dependencias
#       shell: cd /root/samba/samba-4* && bootstrap/generated-dists/debian12/bootstrap.sh

     - name: Parando servicos do samba-4.
       shell: systemctl stop samba-ad-dc

     - name: Update do samba-4.
       shell: cd /root/samba/samba-4* && ./configure && make && make install

     - name: Organizacao de pacotes e pastas.
       shell: rm -rf /root/samba/samba-latest.tar.gz && mv /root/samba/samba-4* /root/samba/tar_old/

     - name: Iniciando o servico do samba4
       shell: systemctl start samba-ad-dc && systemctl restart samba-ad-dc

     - name: Checando os databases
       shell: /usr/local/samba/bin/samba-tool dbcheck --cross-ncs && /usr/local/samba/bin/samba-tool dbcheck --cross-ncs --fix

     - name: Reiniciando o servidor
       shell: sleep 2 && reboot -n
       async: 1
       poll: 0
       ignore_errors: true

     - name: Esperando o servidor voltar
       local_action: wait_for host={{ ansible_ssh_host }} state=started delay=30

### SERVIDORES DE ARQUIVOS E CUPS
- hosts: 192.168.1.6 192.168.1.3 192.168.1.5
  user: root

  tasks:
     - name: Download pacote recente do samba-4
       shell: cd /root/samba && wget https://download.samba.org/pub/samba/samba-latest.tar.gz

     - name: Descompactar pacote samba-4
       shell: cd /root/samba && tar -xvzf samba*

#     - name: Instalacao de dependencias
#       shell: cd /root/samba/samba-4* && bootstrap/generated-dists/debian12/bootstrap.sh

     - name: Parando os servicos do samba4
       shell: /usr/local/samba/sbin/smbd stop && /usr/local/samba/sbin/nmbd stop && /usr/local/samba/sbin/winbindd stop

     - name: Update do samba4
       shell: cd /root/samba/samba-4* && ./configure --without-ad-dc && make && make install

     - name: Organizando pacotes e pastas
       shell: rm -rf /root/samba/samba-latest.tar.gz && mv /root/samba/samba-4* /root/samba/tar_old/

     - name: Iniciando o servico do samba4
       shell: /usr/local/samba/sbin/smbd start && /usr/local/samba/sbin/nmbd start && /usr/local/samba/sbin/winbindd start && /usr/local/samba/sbin/smbd restart && /usr/local/samba/sbin/nmbd restart && /usr/local/samba/sbin/winbindd restart

#     - name: Reiniciando o servidor
#       shell: sleep 2 && reboot -n
#       async: 1
#       poll: 0
#       ignore_errors: true

#     - name: Esperando o servidor voltar
#       local_action: wait_for host={{ ansible_ssh_host }} state=started delay=30
...
