---

# host deve ser um membro do domínio ansible.vagrant; O módulo garantirá que o nome do host seja mydomainclient 
# e usará as credenciais aprovadas para ingressar no domínio, se necessário. 
# Conexão Ansible deve usar credenciais locais, se possível. 
# Se uma reinicialização for necessária, a segunda tarefa acionará uma e aguardará até que o host esteja disponível. 

- hosts: windows 
  gather_facts: no
  
  tasks:
          #- name: Inserindo maquina no dominio de rede 
        - win_domain_membership:
            dns_domain_name: hweqlt.com.br 
            #hostname: {{ ansible_nodename }} 
            domain_admin_user: administrator@hweqlt.com.br
            domain_admin_password: fki#@!5991
            #domain_ou_path: "OU=Windows,OU=Servers,DC=ansible,DC=vagrant"
            state: domain
          register: domain_state

        - win_reboot:
          when: domain_state.reboot_required
...
