---
### FALTA IMPLANTACAO E TESTES
### http://docs.ansible.com/ansible/latest/modules/win_package_module.html#win-package

- hosts: 192.168.1.40 

  tasks:
        - name: Instalacao Sicalc 
          win_package:
             path: http://www.receita.fazenda.gov.br/publico/programas/sicalc/Unico/setup.exe 
             #product_id: '{CF2BEA3C-26EA-32F8-AA9B-331F7E34BA97}' 
             product_id: 'Sicalc Auto Atendimento' 
             arguments:
                - /install
                - /passive
                - /norestart  

...
